In [2]:
#Ques1:Create a 3x3x3 array with random values

import numpy as np
x = np.random.random((3,3,3))
print(x)

[[[0.32790089 0.57049854 0.97318751]
  [0.56225436 0.61307606 0.03177034]
  [0.83836857 0.11000338 0.30762417]]

 [[0.84576269 0.69829375 0.60742609]
  [0.32821753 0.43675844 0.51718044]
  [0.76209407 0.77674104 0.31493272]]

 [[0.0746867  0.24014325 0.42625665]
  [0.17837453 0.8585976  0.69697831]
  [0.41406919 0.11683008 0.64624023]]]


In [3]:
#Ques3:Create a 8x8 matrix and fill it with a checkerboard pattern

import numpy as np
print("Checkerboard pattern:")
x = np.zeros((8,8),dtype=int)
x[1::2,::2] = 1
x[::2,1::2] = 1
print(x)

Checkerboard pattern:
[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [4]:
#Ques5:How to find common values between two arrays?

import numpy as np
array1 = np.array([0, 10, 20, 40, 60])
print("Array1: ",array1)
array2 = [10, 30, 40]
print("Array2: ",array2)
print("Common values between two arrays:")
print(np.intersect1d(array1, array2))

Array1:  [ 0 10 20 40 60]
Array2:  [10, 30, 40]
Common values between two arrays:
[10 40]


In [5]:
#Ques8:Create random vector of size 10 and replace the maximum value by 0

import numpy as np
x = np.random.random(10)
print("Original array:")
print(x)
x[x.argmax()] = 0
print("Maximum value replaced by 0:")
print(x)

Original array:
[0.54801067 0.5924285  0.15893798 0.41161388 0.69899443 0.17248579
 0.2887293  0.91591404 0.62340795 0.03832253]
Maximum value replaced by 0:
[0.54801067 0.5924285  0.15893798 0.41161388 0.69899443 0.17248579
 0.2887293  0.         0.62340795 0.03832253]
